# Generated by Django 3.2.18 on 2023-03-08 20:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
