# Generated by Django 3.2.18 on 2023-03-08 21:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='news_overview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
