# Generated by Django 3.2.18 on 2023-03-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20230309_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='news_overview',
            field=models.TextField(null=True),
        ),
    ]
