# Generated by Django 3.2.18 on 2023-03-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20230311_1214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Published_status',
            new_name='published_status',
        ),
    ]
